#ifndef APPLICATION_BUILD_CONFIG_H_
#define APPLICATION_BUILD_CONFIG_H_

#define FINAL_RELEASE_BUILD 1

#if FINAL_RELEASE_BUILD
#define INTERBOARD_LINK_ENABLE          1U
#define STARFLASH_DEBUG_ENABLE          0U
#define TASK3_PERIODIC_CSV_ENABLE       0U
#define DUAL_LOOP_DIAG_TELEMETRY_ENABLE 0U
#define SPEED_CAL_TELEMETRY_ENABLE      0U
#define ARCH001_TEXT_OUTPUT_ENABLE      0U
#define CONTROL_DEBUG_PRINT_ENABLE      0U
#else
#define INTERBOARD_LINK_ENABLE          0U
#define STARFLASH_DEBUG_ENABLE          1U
#define TASK3_PERIODIC_CSV_ENABLE       1U
#define DUAL_LOOP_DIAG_TELEMETRY_ENABLE 1U
#define SPEED_CAL_TELEMETRY_ENABLE      1U
#define ARCH001_TEXT_OUTPUT_ENABLE      1U
#define CONTROL_DEBUG_PRINT_ENABLE      1U
#endif

#if INTERBOARD_LINK_ENABLE && STARFLASH_DEBUG_ENABLE
#error "UART2 cannot be shared by Interboard and StarFlash"
#endif

#endif